name: job
run-name: ${{github.actor}} is building
# event which triggers this job
on: [push]
jobs:
  build-project:
    # VM used for this job
    runs-on: Ubuntu-latest
    steps:
      # checkout solution to VM
      - uses: actions/checkout@v3

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build .  
